name: Duolingo Leaderboard Position

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-leaderboard-position:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch Duolingo leaderboard position
        env:
          DUOLINGO_USERNAME: ${{ secrets.DUOLINGO_USERNAME }}
          DUOLINGO_PASSWORD: ${{ secrets.DUOLINGO_PASSWORD }}
          DUOLINGO_USER_ID: ${{ secrets.DUOLINGO_USER_ID }}
        run: |
          import requests
          import os
          import json

          def login(username, password):
              url = "https://www.duolingo.com/login"
              data = {"login": username, "password": password}
              headers = {"User-Agent": "Mozilla/5.0"}
              response = requests.post(url, json=data, headers=headers)
              return response.cookies.get("jwt_token")

          def get_leaderboard_position(jwt_token, user_id):
              url = f"https://www.duolingo.com/2017-06-30/users/{user_id}?fields=id,username,league_ranking"
              headers = {
                  "Authorization": f"Bearer {jwt_token}",
                  "User-Agent": "Mozilla/5.0"
              }
              response = requests.get(url, headers=headers)
              user_data = response.json()
              return user_data.get("league_ranking", "Unknown")

          jwt_token = login(os.environ["DUOLINGO_USERNAME"], os.environ["DUOLINGO_PASSWORD"])
          position = get_leaderboard_position(jwt_token, os.environ["DUOLINGO_USER_ID"])

          print(f"Current leaderboard position: {position}")
          print(f"::set-output name=leaderboard_position::{position}")
        shell: python

      - name: Display leaderboard position
        run: echo "Your current Duolingo leaderboard position is ${{ steps.fetch-leaderboard-position.outputs.leaderboard_position }}"
