name: Duolingo Leaderboard Position

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-leaderboard-position:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch Duolingo leaderboard position
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          DUOLINGO_USER_ID: ${{ secrets.DUOLINGO_USER_ID }}
        run: |
          import requests
          import os
          import json

          def get_leaderboard_position(jwt_token, user_id):
              url = f"https://www.duolingo.com/2017-06-30/users/{user_id}?fields=id,username,league_ranking"
              headers = {
                  "Authorization": f"Bearer {jwt_token}",
                  "User-Agent": "Mozilla/5.0"
              }
              response = requests.get(url, headers=headers)
              print(f"Leaderboard request status code: {response.status_code}")
              print(f"Response content: {response.text}")
              user_data = response.json()
              return user_data.get("league_ranking", "Unknown")

          jwt_token = os.environ["DUOLINGO_JWT"]
          user_id = os.environ["DUOLINGO_USER_ID"]
          
          position = get_leaderboard_position(jwt_token, user_id)
          print(f"Current leaderboard position: {position}")
          
          # Use the new way to set output
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              print(f"leaderboard_position={position}", file=fh)
        shell: python

      - name: Display leaderboard position
        run: echo "Your current Duolingo leaderboard position is ${{ steps.fetch-leaderboard-position.outputs.leaderboard_position }}"
