name: Duolingo Leaderboard Position

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-leaderboard-position:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch Duolingo leaderboard position
        env:
          DUOLINGO_JWT: ${{ secrets.DUOLINGO_JWT }}
          DUOLINGO_USER_ID: ${{ secrets.DUOLINGO_USER_ID }}
        run: |
          import requests
          import os
          import json

          def get_user_data(jwt_token, user_id):
              url = f"https://www.duolingo.com/2017-06-30/users/{user_id}?fields=id,username,currentCourse,courses"
              headers = {
                  "Authorization": f"Bearer {jwt_token}",
                  "User-Agent": "Mozilla/5.0"
              }
              response = requests.get(url, headers=headers)
              print(f"User data request status code: {response.status_code}")
              return response.json()

          def get_leaderboard_data(jwt_token, leaderboard_id, user_id):
              url = f"https://duolingo-leaderboards-prod.duolingo.com/leaderboards/{leaderboard_id}/users/{user_id}"
              headers = {
                  "Authorization": f"Bearer {jwt_token}",
                  "User-Agent": "Mozilla/5.0"
              }
              response = requests.get(url, headers=headers)
              print(f"Leaderboard request status code: {response.status_code}")
              return response.json()

          jwt_token = os.environ["DUOLINGO_JWT"]
          user_id = os.environ["DUOLINGO_USER_ID"]
          
          user_data = get_user_data(jwt_token, user_id)
          print(f"User data: {json.dumps(user_data, indent=2)}")
          
          # Assuming the leaderboard ID is part of the current course data
          current_course = user_data.get('currentCourse', {})
          leaderboard_id = current_course.get('leaderboardId')
          
          if leaderboard_id:
              leaderboard_data = get_leaderboard_data(jwt_token, leaderboard_id, user_id)
              print(f"Leaderboard data: {json.dumps(leaderboard_data, indent=2)}")
              
              # Extract ranking information from leaderboard_data
              rank = leaderboard_data.get('rank')
              tier = leaderboard_data.get('tier')
              
              result = f"Rank: {rank}, Tier: {tier}"
          else:
              result = "Could not determine leaderboard ID"
          
          print(f"Leaderboard position: {result}")
          
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
              print(f"leaderboard_position={result}", file=fh)
        shell: python

      - name: Display leaderboard position
        run: echo "Your current Duolingo leaderboard position is ${{ steps.fetch-leaderboard-position.outputs.leaderboard_position }}"
